# Generated by Django 5.1.8 on 2025-05-27 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MindSpaceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('occasionally', 'Occasionally'), ('never', 'Never'), ('rarely', 'Rarely')], default='daily', max_length=50)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mind_space_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mind Space',
                'verbose_name_plural': 'Mind Spaces',
            },
        ),
        migrations.CreateModel(
            name='MoodMirrorEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('excited', 'Excited'), ('calm', 'Calm'), ('frustrated', 'Frustrated'), ('confused', 'Confused'), ('bored', 'Bored'), ('motivated', 'Motivated'), ('overwhelmed', 'Overwhelmed'), ('relaxed', 'Relaxed'), ('grateful', 'Grateful'), ('hopeful', 'Hopeful'), ('lonely', 'Lonely'), ('tired', 'Tired'), ('inspired', 'Inspired'), ('curious', 'Curious')], max_length=50)),
                ('reflection', models.TextField(help_text='Reflect on your day.')),
                ('title', models.CharField(blank=True, help_text='Optional title for the entry.', max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('mind_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindspace.mindspaceprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
