# Generated by Django 5.1.8 on 2025-05-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodmirrorentry',
            name='affirmation',
            field=models.TextField(blank=True, help_text='Optional affirmation for the entry.', null=True),
        ),
    ]
