# Generated by Django 5.1.8 on 2025-06-01 22:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace', '0002_moodmirrorentry_affirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepJournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('sleep_quality', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('reflections', models.TextField(blank=True)),
                ('mind_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_journals', to='mindspace.mindspaceprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoundscapePlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('mind_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soundscape_plays', to='mindspace.mindspaceprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WindDownRitualLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ritual_type', models.CharField(choices=[('gratitude journaling', 'Gratitude Journaling'), ('breathing', 'Breathing'), ('visualization', 'Visualization')], max_length=50)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('mind_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wind_down_rituals', to='mindspace.mindspaceprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
