# Generated by Django 5.1.8 on 2025-06-09 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace', '0003_sleepjournalentry_soundscapeplay_winddownrituallog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundscapeLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('audio_url', models.URLField()),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('mood_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sleepjournalentry',
            old_name='reflections',
            new_name='journal_entry',
        ),
        migrations.RenameField(
            model_name='soundscapeplay',
            old_name='is_active',
            new_name='is_liked',
        ),
        migrations.RemoveField(
            model_name='soundscapeplay',
            name='description',
        ),
        migrations.RemoveField(
            model_name='soundscapeplay',
            name='name',
        ),
        migrations.AddField(
            model_name='sleepjournalentry',
            name='sleep_summary',
            field=models.TextField(blank=True, help_text='How did you sleep last night? E.g., dreams, restfulness, emotions', null=True),
        ),
        migrations.AddField(
            model_name='soundscapeplay',
            name='duration_played',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soundscapeplay',
            name='played_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='soundscapeplay',
            name='soundscape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mindspace.soundscapelibrary'),
        ),
    ]
