# Generated by Django 5.1.8 on 2025-06-09 13:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace', '0004_soundscapelibrary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='winddownrituallog',
            name='entries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='E.g., gratitude entries', size=3),
        ),
        migrations.AddField(
            model_name='winddownrituallog',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Extra data: e.g., breathing cycles', null=True),
        ),
        migrations.AddField(
            model_name='winddownrituallog',
            name='reflection',
            field=models.TextField(blank=True, help_text='Optional reflection text', null=True),
        ),
    ]
