# Generated by Django 5.1.8 on 2025-06-09 14:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace', '0005_winddownrituallog_entries_winddownrituallog_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoulReflection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reflection', models.TextField()),
                ('tag', models.CharField(choices=[('hope', 'Hope'), ('love', 'Love'), ('grief', 'Grief'), ('clarity', 'Clarity')], max_length=30)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('mind_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mindspace.mindspaceprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
