# Generated by Django 5.1.8 on 2025-07-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace', '0008_alter_moodmirrorentry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodmirrorentry',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('excited', 'Excited'), ('scared', 'Scared'), ('teary', 'Teary'), ('hopeful', 'Hopeful'), ('tired', 'Tired'), ('upset', 'Upset')], max_length=50),
        ),
    ]
