# Generated by Django 5.1.8 on 2025-05-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_allow_ovulation_tracker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Canada', max_length=100),
        ),
    ]
