# Generated by Django 5.1.8 on 2025-05-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompthistory',
            name='section',
            field=models.CharField(choices=[('calories', 'Calories'), ('ovulation', 'Ovulation'), ('symptom_tracker', 'Symptom_Checker'), ('none', 'None')], max_length=50),
        ),
    ]
