# Generated by Django 5.1.8 on 2025-05-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_prompthistory_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('ft', 'Feet'), ('in', 'Inches'), ('m', 'Meters')], default='cm', max_length=5),
        ),
    ]
