# Generated by Django 5.1.8 on 2025-05-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_height_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='device_type',
            field=models.CharField(choices=[('android', 'Android'), ('web', 'Web'), ('ios', 'Ios')], default='android', max_length=50),
        ),
    ]
