# Generated by Django 5.1.8 on 2025-05-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_device_token_user_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompthistory',
            name='section',
            field=models.CharField(choices=[('calories', 'Calories'), ('ovulation', 'Ovulation'), ('symptom_tracker', 'Symptom_Checker'), ('mind_space', 'Mind_Space'), ('none', 'None')], max_length=50),
        ),
    ]
