# Generated by Django 5.1.8 on 2025-06-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_prompthistory_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_calories_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_mind_space_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ovulation_tracker_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_trivia_setup',
            field=models.BooleanField(default=False),
        ),
    ]
