# Generated by Django 5.1.8 on 2025-06-27 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_is_calories_setup_user_is_mind_space_setup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompthistory',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
