# Generated by Django 5.1.8 on 2025-05-14 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieQA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.CharField(max_length=100)),
                ('activity_level', models.CharField(max_length=100)),
                ('current_weight', models.FloatField()),
                ('goal_weight', models.FloatField()),
                ('eating_style', models.CharField(max_length=400)),
                ('reminder', models.CharField(max_length=400)),
                ('allow_smart_food_suggestions', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
