# Generated by Django 5.1.8 on 2025-05-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_calorieqa_goal_timeline_loggedmeal_suggestedmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedmeal',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loggedmeal',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loggedmeal',
            name='fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loggedmeal',
            name='protein',
            field=models.IntegerField(default=0),
        ),
    ]
