# Generated by Django 5.1.8 on 2025-05-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0004_alter_calorieqa_user_loggedworkout_suggestedworkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedworkout',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
