# Generated by Django 5.1.8 on 2025-05-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0005_suggestedworkout_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggedworkout',
            old_name='calories_burned',
            new_name='estimated_calories_burned',
        ),
        migrations.RenameField(
            model_name='loggedworkout',
            old_name='workout_type',
            new_name='title',
        ),
        migrations.AddField(
            model_name='loggedworkout',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loggedworkout',
            name='intensity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
    ]
