# Generated by Django 5.1.8 on 2025-05-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0006_rename_calories_burned_loggedworkout_estimated_calories_burned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorieqa',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', max_length=5),
        ),
    ]
