# Generated by Django 5.1.8 on 2025-05-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0007_calorieqa_weight_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedworkout',
            name='steps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
