# Generated by Django 5.1.8 on 2025-05-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0008_loggedworkout_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedmeal',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
