# Generated by Django 5.1.8 on 2025-05-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0009_loggedmeal_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedmeal',
            name='number_of_servings',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
