# Generated by Django 5.1.8 on 2025-05-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0010_loggedmeal_number_of_servings'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedmeal',
            name='measurement_unit',
            field=models.CharField(choices=[('serving', 'Serving'), ('gram', 'Gram'), ('slice', 'Slice')], default='serving', max_length=10),
        ),
    ]
