# Generated by Django 5.1.8 on 2025-07-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0011_loggedmeal_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorieqa',
            name='reminder',
            field=models.CharField(choices=[('daily', 'Daily'), ('only if I forget', 'Only if I forget'), ('no thanks', 'No thanks')], default='daily', max_length=400),
        ),
    ]
