# Generated by Django 5.1.8 on 2025-07-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0012_alter_calorieqa_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggedmeal',
            old_name='number_of_servings',
            new_name='number_of_servings_or_gram_or_slices',
        ),
    ]
