# Generated by Django 5.1.8 on 2025-07-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0014_usercaloriestreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedmeal',
            name='measurement_unit',
            field=models.CharField(choices=[('servings', 'Serving'), ('grams', 'Gram'), ('slice', 'Slice')], default='serving', max_length=10),
        ),
    ]
