# Generated by Django 5.1.8 on 2025-07-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0015_alter_loggedmeal_measurement_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedmeal',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='suggestedmeal',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
