# Generated by Django 5.1.8 on 2025-08-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0016_suggestedmeal_is_template_alter_suggestedmeal_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestedmeal',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='loggedmeal',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
    ]
