# Generated by Django 5.1.8 on 2025-07-19 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_fevertriggers_sensationdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='location',
        ),
        migrations.AddField(
            model_name='symptom',
            name='body_areas',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='symptom',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='symptoms.symptomsession'),
        ),
    ]
