# Generated by Django 5.1.8 on 2025-07-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0003_remove_symptom_location_symptom_body_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomanalysis',
            name='user_report',
            field=models.TextField(blank=True, help_text='Formatted AI narrative for user/doctor.'),
        ),
    ]
