# Generated by Django 5.1.8 on 2025-06-27 17:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_tag', models.CharField(blank=True, help_text='Context tag for the insight', max_length=50, null=True)),
                ('date', models.DateField()),
                ('insight_type', models.CharField(choices=[('insight', 'Insight'), ('mood', 'Mood Insight'), ('affirmation', 'Affirmation'), ('other', 'Other')], max_length=20)),
                ('insights', models.JSONField(default=list, help_text='List of daily insights/affirmations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date', 'context_tag', 'insight_type'], name='utils_usera_user_id_b9b25e_idx')],
                'unique_together': {('user', 'date', 'insight_type')},
            },
        ),
    ]
