# Generated by Django 5.1.8 on 2025-07-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovulations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyclesetup',
            name='is_regular',
        ),
        migrations.AddField(
            model_name='cyclesetup',
            name='current_focus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cyclesetup',
            name='regularity',
            field=models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular'), ('prefer_not_to_say', 'Prefer not to say')], default='regular', max_length=20),
        ),
    ]
