# Generated by Django 5.1.8 on 2025-07-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovulations', '0002_remove_cyclesetup_is_regular_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ovulationlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='ovulationlog',
            unique_together=set(),
        ),
    ]
