# Generated by Django 5.1.8 on 2025-07-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovulations', '0003_alter_ovulationlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cyclestate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='cycleinsight',
            name='confidence',
            field=models.CharField(choices=[('low', 'Low'), ('mid', 'Mid'), ('high', 'High')], default='mid', max_length=10),
        ),
    ]
