# Generated by Django 5.1.8 on 2025-07-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovulations', '0004_alter_cyclestate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovulationlog',
            name='sex_purpose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
